// Copyright (c) 2026 Ivan Tugay
// SPDX-License-Identifier: GPL-3.0-or-later
// Licensed under GPL-3.0 or later; see https://www.gnu.org/licenses/gpl-3.0.html

//! `rtok completions <shell>` (T53.2, T317): clap_complete's shells plus Clink, the completion
//! system `cmd.exe` gets through <https://chrisant996.github.io/clink/>. All of them come from
//! the same clap tree as `--help`.

use std::io::{self, Write};

use clap::builder::PossibleValue;
use clap::{Arg, Command, ValueEnum, ValueHint};
use clap_complete::Generator;

pub mod install;
pub mod picker;

/// Shells `rtok completions` writes for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum Shell {
    Bash,
    Zsh,
    Fish,
    Powershell,
    Elvish,
    // `cmd.exe` through Clink (a Lua argmatcher)
    Clink,
}

impl Shell {
    /// The name `rtok completions <shell>` takes.
    pub fn name(self) -> String {
        let v = self
            .to_possible_value()
            .expect("every shell is a listed value");
        v.get_name().to_string()
    }
}

/// Write the completion script for `shell` to `w`.
pub fn generate(shell: Shell, mut cmd: Command, w: &mut dyn Write) {
    use clap_complete::Shell as C;
    let name = cmd.get_name().to_string();
    match shell {
        Shell::Bash => clap_complete::generate(C::Bash, &mut cmd, name, w),
        Shell::Zsh => clap_complete::generate(C::Zsh, &mut cmd, name, w),
        Shell::Fish => clap_complete::generate(C::Fish, &mut cmd, name, w),
        Shell::Powershell => clap_complete::generate(C::PowerShell, &mut cmd, name, w),
        Shell::Elvish => clap_complete::generate(C::Elvish, &mut cmd, name, w),
        Shell::Clink => clap_complete::generate(Clink, &mut cmd, name, w),
    }
}

/// Clink argmatcher generator. `clap_complete_clink` 1.0.0 was the ready option; it lists hidden
/// subcommands, leaves `\` unescaped in Lua strings and completes no option or positional values,
/// and has had no change since 2025-10, so this is the small in-tree version (T317).
pub struct Clink;

impl Generator for Clink {
    fn file_name(&self, name: &str) -> String {
        format!("{name}.lua")
    }

    fn generate(&self, cmd: &Command, buf: &mut dyn Write) {
        self.try_generate(cmd, buf)
            .expect("failed to write the Clink script");
    }

    fn try_generate(&self, cmd: &Command, buf: &mut dyn Write) -> io::Result<()> {
        let bin = cmd.get_bin_name().unwrap_or_else(|| cmd.get_name());
        writeln!(
            buf,
            "-- Clink completions for {bin}, generated by `{bin} completions clink`.\n\
             -- Put this file in a Clink script directory (`clink info` lists them)."
        )?;
        writeln!(
            buf,
            "{}",
            matcher(cmd, &format!("clink.argmatcher({})", lua(bin)), 0)
        )
    }
}

/// `head` followed by the chained `:addarg` / `:addflags` / `:adddescriptions` calls for `cmd`.
fn matcher(cmd: &Command, head: &str, depth: usize) -> String {
    let pad = " ".repeat(4 * depth + 2);
    let mut out = head.to_string();
    let mut descriptions = Vec::new();
    let subs: Vec<&Command> = cmd.get_subcommands().filter(|s| !s.is_hide_set()).collect();
    if subs.is_empty() {
        for arg in cmd.get_positionals().filter(|a| !a.is_hide_set()) {
            out.push_str(&format!("\n{pad}:addarg({})", values(arg)));
        }
    } else {
        let items: Vec<String> = subs
            .iter()
            .flat_map(|s| {
                let inner = matcher(s, "clink.argmatcher()", depth + 1);
                let about = s.get_about().map(|a| a.to_string()).unwrap_or_default();
                s.get_name_and_visible_aliases()
                    .into_iter()
                    .map(|n| {
                        descriptions.push(format!("[{}] = {}", lua(n), lua(&about)));
                        format!("{} .. {inner}", lua(n))
                    })
                    .collect::<Vec<_>>()
            })
            .collect();
        out.push_str(&format!(
            "\n{pad}:addarg({{\n{pad}  {}\n{pad}}})",
            items.join(&format!(",\n{pad}  "))
        ));
    }
    let mut flags = Vec::new();
    for arg in cmd
        .get_arguments()
        .filter(|a| !a.is_positional() && !a.is_hide_set())
    {
        let takes = arg.get_num_args().is_some_and(|n| n.takes_values());
        let about = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
        let mut names: Vec<String> = arg
            .get_long_and_visible_aliases()
            .unwrap_or_default()
            .into_iter()
            .map(|l| format!("--{l}"))
            .collect();
        names.extend(
            arg.get_short_and_visible_aliases()
                .unwrap_or_default()
                .into_iter()
                .map(|s| format!("-{s}")),
        );
        for n in names {
            flags.push(if takes {
                format!("{} .. clink.argmatcher():addarg({})", lua(&n), values(arg))
            } else {
                lua(&n)
            });
            descriptions.push(format!("[{}] = {}", lua(&n), lua(&about)));
        }
    }
    if !flags.is_empty() {
        out.push_str(&format!("\n{pad}:addflags({{ {} }})", flags.join(", ")));
    }
    if !descriptions.is_empty() {
        out.push_str(&format!(
            "\n{pad}:adddescriptions({{ {} }})",
            descriptions.join(", ")
        ));
    }
    out
}

/// What completes in an argument slot: its possible values, file names for a path, else nothing.
fn values(arg: &Arg) -> String {
    let possible: Vec<PossibleValue> = arg
        .get_possible_values()
        .into_iter()
        .filter(|v| !v.is_hide_set())
        .collect();
    if !possible.is_empty() {
        let names: Vec<String> = possible.iter().map(|v| lua(v.get_name())).collect();
        return format!("{{ {} }}", names.join(", "));
    }
    match arg.get_value_hint() {
        ValueHint::AnyPath
        | ValueHint::FilePath
        | ValueHint::DirPath
        | ValueHint::ExecutablePath => "clink.filematches".into(),
        _ => "{}".into(),
    }
}

/// A Lua string literal: `\`, `"` and control characters escaped, newlines folded to spaces.
fn lua(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' | '\r' | '\t' => out.push(' '),
            c if c.is_control() => {}
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    fn clink(cmd: Command) -> String {
        let mut out = Vec::new();
        generate(Shell::Clink, cmd, &mut out);
        String::from_utf8(out).unwrap()
    }

    fn fixture() -> Command {
        Command::new("demo")
            .arg(
                Arg::new("path")
                    .long("path")
                    .value_hint(ValueHint::FilePath),
            )
            .subcommand(
                Command::new("pick")
                    .about(r#"Say "hi" \ bye"#)
                    .arg(Arg::new("shell").value_parser(["bash", "clink"])),
            )
            .subcommand(Command::new("secret").hide(true))
    }

    #[test]
    fn clink_names_values_and_skips_hidden() {
        let lua = clink(fixture());
        assert!(lua.contains(r#"clink.argmatcher("demo")"#), "{lua}");
        assert!(lua.contains(r#""pick" .. clink.argmatcher()"#), "{lua}");
        assert!(lua.contains(r#":addarg({ "bash", "clink" })"#), "{lua}");
        assert!(
            lua.contains(r#""--path" .. clink.argmatcher():addarg(clink.filematches)"#),
            "{lua}"
        );
        assert!(lua.contains(r#"["pick"] = "Say \"hi\" \\ bye""#), "{lua}");
        assert!(!lua.contains("secret"), "{lua}");
    }

    #[test]
    fn clink_covers_every_rtok_subcommand_and_parses() {
        let lua = clink(crate::cli::Cli::command());
        for sub in crate::cli::Cli::command()
            .get_subcommands()
            .filter(|s| !s.is_hide_set())
        {
            assert!(
                lua.contains(&format!("\"{}\" ..", sub.get_name())),
                "{}",
                sub.get_name()
            );
        }
        // Syntax check where a working Lua compiler is on PATH (CI and dev machines may lack
        // one; a version-manager shim with no version set fails `-v` and counts as absent).
        let luac =
            |args: &[&std::ffi::OsStr]| std::process::Command::new("luac").args(args).output();
        if !luac(&["-v".as_ref()]).is_ok_and(|o| o.status.success()) {
            return;
        }
        let file = crate::testutil::tmp_dir("clink").join("rtok.lua");
        std::fs::write(&file, &lua).unwrap();
        let out = luac(&["-p".as_ref(), file.as_os_str()]).unwrap();
        assert!(
            out.status.success(),
            "luac: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
}
